import java.util.Scanner;

public class CharacterAtIndex {
    public static void main(String[] args) {
        Scanner sc = new Scanner(System.in);

        System.out.print("Enter a string: ");
        String str = sc.nextLine();

        System.out.print("Enter the index number: ");
        int index = sc.nextInt();

   
        if (index >= 0 && index < str.length()) {
         
            char ch = str.charAt(index);
            System.out
        }
    }    
}    